Eye gouging/casino update
StoneAndStar/RockStar pull request #42
Opened 2022-07-06 07:07 UTC by SeeminglyTypicalUsername

## About The Pull Request

This PR ports eye gouging/poking (bigdaddysanta made this) and improves upon the casinos with new carpets, roulette tables, and a sign for the shark club which is animated.
![image](https://user-images.githubusercontent.com/94082600/177490024-7115c827-0853-4824-a770-c49ee8e1559f.png)
![image](https://user-images.githubusercontent.com/94082600/177490086-5ce62af8-f006-4038-891c-d25e3bdbdedb.png)

## Why It's Good For The Game

Eyegouging adds in some interesting RP options and combat abilities and were in some dire need of individualization. 

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

:cl:
add: eye gouging
add: eye poking
add: shark club sign
add: roulette tables
add:  multiple new carpets
add:  mordino armory
/:cl:

2022-07-06 15:26 UTC, hermaplusplus requested changes
Eye gouging is not a map feature, and should be in a separate pull request targeting the main branch. Please do not bundle game mechanics with map changes.

This PR also includes the addition of a roulette table in code, which is already present in PR #40 targeting `main`. Please remove it from this PR, as it will be in the main code soon. You should be fine to leave the map files as they are.

2022-07-07 06:30 UTC, hermaplusplus approved these changes

2022-07-07 06:33 UTC, hermaplusplus commented
**Note to maintainers**: Before this PR is merged, #40 must be merged and `main` must be merged into `maps/newreno`. In lieu of CI on the mapping branches, test for runtimes thoroughly.

2022-07-07 19:19 UTC, Kitsunemitsu approved these changes
Took a look, Everything looks good.
We really do need to get MapDiffBot for easier map PR reviews

2022-07-07 19:23 UTC, merged